version: "3.8"

name: "poll_bot-local"

services:
  poll_bot:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: poll_bot
    stdin_open: true
    command: "/start_bot"
    volumes:
      - ./src:/app:z
      - ./media:/media:z
    env_file:
      - ./.envs/.production/.poll_bot

  admin:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: poll_bot
    stdin_open: true
    command: "/start_admin"
    volumes:
      - ./src:/app:z
      - ./media:/media:z
    env_file:
      - ./.envs/.production/.poll_bot
    ports:
      - "8002:8000"
