"""Initial

Revision ID: e574433d51f5
Revises: 
Create Date: 2023-12-14 01:42:29.742679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e574433d51f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('result_key', sa.String(length=255), nullable=True),
    sa.Column('message_txt', sa.String(length=255), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_results_id'), 'poll_results', ['id'], unique=False)
    op.create_index(op.f('ix_poll_results_result_key'), 'poll_results', ['result_key'], unique=True)
    op.create_table('poll_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('step_key', sa.String(length=255), nullable=True),
    sa.Column('message_txt', sa.String(length=255), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_steps_id'), 'poll_steps', ['id'], unique=False)
    op.create_index(op.f('ix_poll_steps_step_key'), 'poll_steps', ['step_key'], unique=True)
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ptype', sa.String(length=30), nullable=True),
    sa.Column('p_telegram_id', sa.String(length=255), nullable=True),
    sa.Column('chat_id', sa.String(length=255), nullable=True),
    sa.Column('dialog_machine', sa.LargeBinary(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['poll_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_id'), 'polls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_polls_id'), table_name='polls')
    op.drop_table('polls')
    op.drop_index(op.f('ix_poll_steps_step_key'), table_name='poll_steps')
    op.drop_index(op.f('ix_poll_steps_id'), table_name='poll_steps')
    op.drop_table('poll_steps')
    op.drop_index(op.f('ix_poll_results_result_key'), table_name='poll_results')
    op.drop_index(op.f('ix_poll_results_id'), table_name='poll_results')
    op.drop_table('poll_results')
    # ### end Alembic commands ###
